### ISSUE TITLE
Buttons werden größer und stoßen an den Rand

### ISSUE THREAD

**Issue by Clark2309** [SoltauFintel/stechuhr#22]
Unschön: Wenn die Buttons durch einen langen Text größer werden, stoßen die rechten Buttons direkt an den Fensterrand.

**Comment by SoltauFintel** [comment]
Lösungsidee: Textlänge begrenzen und mit "..." enden lassen. Plus Tooltip.

**Comment by SoltauFintel** [comment]
erledigt
